color0 #22252f
color1 #fd4663
color2 #6782e4
color3 #8f6ee9
color4 #b666cc
color5 #93a6ec
color6 #ae96e9
color7 #f2f2f3
color8 #636773
color9 #fd4663
color10 #6782e4
color11 #8f6ee9
color12 #b666cc
color13 #93a6ec
color14 #ae96e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a1c24
background            #1a1c24
foreground            #f2f2f3
selection_foreground  #afb0b6
selection_background  #22252f
active_border_color   #6782e4
inactive_border_color #22252f
url_color             #6782e4

active_tab_foreground   #181b25
active_tab_background   #6782e4
inactive_tab_foreground #afb0b6
inactive_tab_background #22252f
cursor_trail_color      #afb0b6
