color0 #241b26
color1 #2f2a3f
color2 #46354a
color3 #6c3cb2
color4 #7e5f83
color5 #eed5d9
color6 #d9c2c6
color7 #e4ccd0
color8 #877bb6
color9 #de5b44
color10 #a84a73
color11 #c965bf
color12 #9c5fce
color13 #6a9eb5
color14 #78a38f
color15 #a3a079

cursor #eed5d9
cursor_text_color #9c5fce
background #241b26
foreground            #f2f2f3
selection_foreground  #afb0b6
selection_background  #22252f
active_border_color   #6782e4
inactive_border_color #22252f
url_color             #6782e4

active_tab_foreground   #181b25
active_tab_background   #6782e4
inactive_tab_foreground #afb0b6
inactive_tab_background #22252f
cursor_trail_color      #afb0b6

